[package]
name = "rustnes"
version = "0.1.0"
authors = ["Youness <kafia.youness@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags ="1.2.1"
console = "0.9.1"